# SEBA
# NEW SERVICE for External Access
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trino # Selector must match your Cassandra pods
  name: trino-external # Give it a different name
  namespace: trino
spec:
  # clusterIP: None # DO NOT set clusterIP: None here
  ports:
    - port: 8080 # Port of the service
      targetPort: 8080 # Port on the container
      protocol: TCP
      name: trinotlb # Give it a name for clarity
  selector:
    app: trino # This must match the labels on your Cassandra pods
  type: LoadBalancer # This is the service type for external access