apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tb-node
  namespace: thingsboard
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tb-node
  serviceName: tb-node
  template:
    metadata:
      labels:
        app: tb-node
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - tb-node
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: TB_SERVICE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: TB_SERVICE_TYPE
          value: monolith
        - name: TB_QUEUE_TYPE
          value: in-memory
        - name: HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE
          value: "false"
        - name: COAP_BIND_ADDRESS
          value: 0.0.0.0
        - name: COAP_BIND_PORT
          value: "5683"
        - name: COAP_TIMEOUT
          value: "10000"
        - name: REPORTS_SERVER_ENDPOINT_URL
          value: http://tb-web-report:8383
        - name: TB_LICENSE_SECRET
          valueFrom:
            secretKeyRef:
              key: license-key
              name: tb-license
        - name: TB_LICENSE_INSTANCE_DATA_FILE
          value: /data/instance-license-$(TB_SERVICE_ID).data
        - name: CASSANDRA_HOST
          value: cassandra.thingsboard.svc.cluster.local
        envFrom:
        - configMapRef:
            name: tb-node-db-config
        image: thingsboard/tb-pe-node:4.0.1PE
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 460
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: server
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        - containerPort: 8883
          name: mqtts
          protocol: TCP
        - containerPort: 5683
          name: coap
          protocol: UDP
        - containerPort: 5684
          name: coaps
          protocol: UDP
        - containerPort: 5685
          name: lwm2m
          protocol: UDP
        - containerPort: 5686
          name: lwm2ms
          protocol: UDP
        - containerPort: 5687
          name: lwm2m-bs
          protocol: UDP
        - containerPort: 5688
          name: lwm2ms-bs
          protocol: UDP
        - containerPort: 7070
          name: edge
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: tb-node-config
        - mountPath: /var/log/thingsboard
          name: tb-node-logs
        - mountPath: /data
          name: tb-node-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        role: main
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 799
        runAsNonRoot: true
        runAsUser: 799
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: conf
            path: thingsboard.conf
          - key: logback
            path: logback.xml
          name: tb-node-config
        name: tb-node-config
      - emptyDir: {}
        name: tb-node-logs
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: tb-node-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem
