# SEBA
# NEW SERVICE for External Access
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra # Selector must match your Cassandra pods
  name: cassandra-external # Give it a different name
  namespace: thingsboard
spec:
  # clusterIP: None # DO NOT set clusterIP: None here
  ports:
    - port: 9042 # Port of the service
      targetPort: 9042 # Port on the container
      protocol: TCP
      name: cql # Give it a name for clarity
  selector:
    app: cassandra # This must match the labels on your Cassandra pods
  type: LoadBalancer # This is the service type for external access