apiVersion: v1
kind: Pod
metadata:
  name: dummy-high-demand
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "8"
        memory: "16Gi"